version: "3.8"

services:
  wishtree-server:
    image: wishtree-server
    build:
      context: ./
    ports:
      - "12347:4000"
    platform: linux/arm64/v8
    volumes:
      - wish-tree-server-data:/data
    restart: unless-stopped
volumes:
  wish-tree-server-data:
